[project]
name = "zpp_color"
version = "1.0.4"
description = "Colorisation de texte dans un terminal"
mainfile = "color.py"
requires-python = ">=3.6"

[project.metadata]
authors = ["ZephyrOff"]
maintainers = []
readme = "README.md"
license = "MIT License"
license_file = "LICENSE"
keywords = []
classifiers = []
copyright = ""
changelog = "changelog.md"

[project.urls]
changelog = ""
homepage = "https://github.com/ZephyrOff/zpp_color"
documentation = "https://github.com/ZephyrOff/zpp_color"

[project.dependencies.windows]

[project.dependencies.linux]

[project.build]
packages = ["os", "ctypes"]
includes = []
excludes = []
include_files = []
optimize = 0
no_compress = false
GUI = false
icon = ""

[project.wheel]
platforms = "ALL"

[project.wheel.entry_points]
console_scripts = []
